### ISSUE TITLE
Shouldn't the output of the script reference the response, not request?

### ISSUE THREAD

**Issue by ycheapopo** [trustyou/example-bulk-api#2]
in crawl_bulk_api.js
Line 115:
            print("Ok: {}".format(request))
gives no useful information. 
Shouldn't output be 
            print("Ok: {}".format(response))
?

**Comment by sportsracer** [comment]
That's just debug output, telling you that the request returned data successfully.

After that line, one should enter their business logic, pulling needed data from the `response` object.

Do you represent a hospitality company? If so, I'm happy to put you in contact with a TrustYou team member to discuss your use case for the TrustYou API.
